fix: agentctl config dump not working with remote models
ligato/vpp-agent pull request #1863
Opened 2022-08-09 12:38 UTC by pemoticak

#### This PR:
- fixes `agentctl config dump` to work with remote models (fix is very similar to #1860)
- refactors the scheduler client API to use a type more suited for JSON (un)marshalling
- ModelList now registers the models that it fetches into the DefaultRegistry

These changes (mainly the ModelList one) fix some problems with trailing slashes in remote model key prefixes (for example when running `agentctl model list/inspect`).

Signed-off-by: Peter Motičák [peter.moticak@pantheon.tech](mailto:peter.moticak@pantheon.tech)

2022-09-09 11:24 UTC, ondrej-fabry commented
is this ready for merge?

2022-09-09 11:47 UTC, pemoticak commented
Yes the fix itself works and should be ready for merge but it doesn't have an e2e test. The test could be added in a separate PR at a later time though.

2022-09-12 12:43 UTC, fgschwan requested changes

2022-09-12 12:43 UTC, fgschwan commented on plugins/kvscheduler/api/txn_record.go
> +type RecordedKVWithMetadata struct {
Just add some explaining godoc for this new structure. When i dig deeper for the difference between this and KVWithMetadata, i got only added ProtoMsgName field (in RecordedProtoMessage struct somewhere in internal). So please state clearly why we need it, what is the added value (+maybe compare with KVWithMetadata).

2022-09-12 14:16 UTC, fgschwan approved these changes

2022-09-19 11:36 UTC, merged